Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.network "forwarded_port", guest: 80, host: 8089
    /config.vm.network "private_network", ip: "192.168.50.4"/
    /config.vm.network "private_network", type: "dhcp"/
    /config.vm.network "public_network", ip: "someip"/
    config.vm.network "public_network"
end