$script_mysql = <<-SCRIPT
    apt update && \
    apt install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"

    /config.vm.network "private_network", type: "dhcp"/
    /config.vm.network "public_network", ip: "someip"/
    /config.vm.network "public_network"/

    config.vm.define "mysqldb" do |mysql|
        mysql.vm.network "forwarded_port", guest: 80, host: 8090
        mysql.vm.network "private_network", ip: "192.168.1.24"
    
        mysql.vm.synced_folder "./configs", "/configs"
        mysql.vm.synced_folder ".", "/vagrant", disabled: true

        mysql.vm.provision "shell", inline: $script_mysql
        mysql.vm.provision "shell", inline: "cat /configs/mysql.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
        mysql.vm.provision "shell", inline: "service mysql restart"

        mysql.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
    end

    config.vm.define "phpweb" do |phpweb|
        phpweb.vm.network "forwarded_port", guest: 80, host: 8089
        phpweb.vm.network "private_network", ip: "192.168.1.25"
    end

end