$script_mysql = <<-SCRIPT
    apt-get update && \
    apt-get install -y mysql-server-5.7 && \
    mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    /config.vm.network "private_network", type: "dhcp"/
    /config.vm.network "public_network", ip: "someip"/
    /config.vm.network "public_network"/

    config.vm.define "mysqldb" do |mysql|
        mysql.vm.network "public_network", ip: "192.168.1.24"
    
        mysql.vm.synced_folder "./configs", "/configs"
        mysql.vm.synced_folder ".", "/vagrant", disabled: true

        mysql.vm.provision "shell", inline: $script_mysql
        mysql.vm.provision "shell", inline: "cat /configs/mysql.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
        mysql.vm.provision "shell", inline: "service mysql restart"

        mysql.vm.provision "shell", inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
    end

    config.vm.define "phpweb" do |phpweb|
        phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
        phpweb.vm.network "public_network", ip: "192.168.1.25"

        phpweb.vm.provision "shell", inline: "sudo apt-get update && apt-get install puppet -y"

        phpweb.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./configs/manifests"
            puppet.manifest_file = "phpweb.pp"
        end
    end
end